version: "3.8"

services:
  mongo:
    image: mongo:4.4.1
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017

  redis:
    image: redis:6.0.9
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379

volumes:
  mongo_data:
  redis_data:
